cache:
  paths:
    - node_modules/
    - client/node_modules/
    - server/node_modules/

stages:
  - build
  - deploy

develop-build:
  image: docker:latest
  stage: build
  only:
    - develop
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 172.104.104.171 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "build for develop"
    # - npm install
    # - npm run build
    - echo 'build completed'

develop-deploy:
  stage: deploy
  only:
    - develop
  script:
    - echo "deploy to develop server"
    # - sshpass -p ${SSH_PASSWORD} ssh -o StrictHostKeyChecking=no root@172.104.104.171
    - ssh root@172.104.104.171
    - cd /var/www/wowo.web
    - git pull
    - ${GIT_USERNAME}
    - ${GIT_PASSWORD}
    - pm2 restart index
    - echo 'deploy completed'